# Generated by Django 2.2.3 on 2019-10-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speechscript',
            name='is_deleted',
        ),
    ]
