# Generated by Django 2.2.3 on 2019-07-30 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_auto_20190712_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechscript',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
