# Generated by Django 2.2.3 on 2019-10-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_remove_speechscript_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechscript',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제 유무'),
        ),
    ]
