# Generated by Django 2.2.3 on 2019-10-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0004_auto_20190814_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechscript',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제 유무'),
        ),
    ]
